#!/bin/bash
#PBS -l select=1:ncpus=4:mpiprocs=4
#PBS -l walltime=2:0:0

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
export OMP_NUM_THREADS=1

cd ${PBS_O_WORKDIR}

module load intel/19.0.0.117

export VASP="${HOME}/apps/bin/vasp_std"

############################ Script Start ##############################

totT=0

rm EvsA EvsV evfit.in evfit.4 grace SUMMARY.hcp

##### Create POSCAR #####
for a in `seq -w 3.5 0.1 4.5`
do
echo "a= $a"

b=`echo $a|awk '{print $1*3**.5}'`
c=`echo $a|awk '{print $1*1.633}'`

cat >POSCAR <<!
Al HCP
1.0
$a  0.00  0.00
0.00   $b 0.00
0.00   0.00  $c
4
Direct
0.25  0.333  0.25
0.75  0.833  0.25
0.25  0.00   0.75
0.75  0.50   0.75
!

mpirun $VASP

V=`grep volume/ion OUTCAR|awk '{print $5}'`
E=`tail -n1 OSZICAR | awk '{ print $5/4}'`
T=`grep 'CPU time' OUTCAR |awk '{print $6}'`
totT=`echo $totT $T|awk '{print $1+$2}'`
echo $a $T >> TvsA
V_3=`echo $V|awk '{print $1**(1./3.)}'`

echo $a $E >> EvsA
echo $V $E >> EvsV
echo $V_3 $E >> evfit.in

done

# TODO: evfit to be implemented in python script 

# cat <<! | evfit
# GEN
# 1
# 4
# evfit.in
# evfit.4
# !

# Emin=`grep Emin evfit.4|awk '{print $2}'`
# A0=`grep A0 evfit.4|awk '{print $2}'`
# K0=`grep A0 evfit.4|awk '{print $4}'`

# V0=`echo $A0|awk '{print $1**3}'`

# tail +5 evfit.4|awk '{print $1,"\t", $2,"\t", $3}' > grace

# echo "Data for Al in HCP" >> SUMMARY.hcp
# echo "=================================================" >> SUMMARY.hcp
# echo "Equilibrium Energy per Atom    = $Emin">>SUMMARY.hcp
# echo "Equilibrium Volume             = $V0">>SUMMARY.hcp
# echo "Bulk Modulus                   = $K0">>SUMMARY.hcp
# echo "Total CPU time (sec)           = $totT">>SUMMARY.hcp

############################ Script End ##############################