#!/bin/bash
#PBS -l select=1:ncpus=4:mpiprocs=4
#PBS -l walltime=2:0:0
#PBS -P 11001317

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
export OMP_NUM_THREADS=1

cd ${PBS_O_WORKDIR}

module load intel/19.0.0.117

export VASP="${HOME}/apps/bin/vasp_std"

############################ Script Start ##############################

totT=0

rm EvsA EvsV evfit.4 grace SUMMARY.dia

for a in `seq -w 3 0.25 6`
do
echo "a= $a"

cat >POSCAR <<!
Al Diamond
1.0
$a  0.00  0.00
0.00   $a 0.00
0.00   0.00  $a
8
Direct
0.10  0.10  0.10
0.60  0.60  0.10
0.60  0.10  0.60
0.10  0.60  0.60
0.35  0.35  0.35
0.85  0.85  0.35
0.85  0.35  0.85
0.35  0.85  0.85
!

mpirun $VASP

V=`grep volume/ion OUTCAR|awk '{print $5}'`
E=`tail -n1 OSZICAR | awk '{ print $5/8}'`
totT=`echo $totT $T|awk '{print $1+$2}'`
V_3=`echo $V|awk '{print $1**(1./3.)}'`

echo $a $E >> EvsA
echo $V $E >> EvsV
echo $V_3 $E >> evfit.in

done

# TODO: evfit to be implemented in python script 

# cat <<! | evfit
# GEN
# 1
# 4
# evfit.in
# evfit.4
# !

# Emin=`grep Emin evfit.4|awk '{print $2}'`
# A0=`grep A0 evfit.4|awk '{print $2}'`
# K0=`grep A0 evfit.4|awk '{print $4}'`

# V0=`echo $A0|awk '{print $1**3}'`

# tail +5 evfit.4|awk '{print $1,"\t", $2,"\t", $3}' > grace

# echo "Data for Al in Diamond" >> SUMMARY.dia
# echo "=================================================" >> SUMMARY.dia
# echo "Equilibrium Energy per Atom    = $Emin">>SUMMARY.dia
# echo "Equilibrium Volume             = $V0">>SUMMARY.dia
# echo "Equilibrium Lattice constant   = $A0">>SUMMARY.dia
# echo "Bulk Modulus                   = $K0">>SUMMARY.dia
# echo "Total CPU time (sec)           = $totT">>SUMMARY.dia

############################ Script End ##############################