#!/bin/bash
#PBS -l select=1:ncpus=4:mpiprocs=4
#PBS -l walltime=2:0:0
#PBS -P 11001317


export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
export OMP_NUM_THREADS=1

cd ${PBS_O_WORKDIR}

module load intel/19.0.0.117
export VASP="${HOME}/apps/bin/vasp_std"

############################ Script Start ##############################

mpirun  $VASP

############################ Script End   ##############################
